### ISSUE TITLE
Proper redirections

### ISSUE THREAD

**Issue by hemanth** [ForbesLindesay/brcdn.org#1]
`www` vs `non-www` URL as in [this](https://brcdn.org) and [that](https://www.brcdn.org) should land at the same page. //cc @ForbesLindesay

**Comment by ForbesLindesay** [comment]
Done, with the exception that "https://brcdn.org/qWQsQgoIKxqLm7k1j5WHfhACgw.js" works but "https://www.brcdn.org/qWQsQgoIKxqLm7k1j5WHfhACgw.js" does not.  I think this is probably fine.

**Comment by hemanth** [comment]
:+1:
