### ISSUE TITLE
brcdn.org is down

### ISSUE THREAD

**Issue by voltrevo** [ForbesLindesay/brcdn.org#11]
<img width="1248" alt="screen shot 2016-03-03 at 10 56 36 am" src="https://cloud.githubusercontent.com/assets/9291586/13479964/c6b4db20-e12e-11e5-8a4a-b48d44078e90.png">

It's been a couple of days now. Do you expect it to come back online anytime soon? Could you please give an update?

**Comment by ForbesLindesay** [comment]
It should be back now.  I missed the pings on notification.

**Comment by voltrevo** [comment]
Sweet :-D
